### ISSUE TITLE
Blueetooth thermal printer not found the driver

### ISSUE THREAD

**Issue by okkypt** [katzer/cordova-plugin-printer#190]
i have Bluetooth thermal printer, with type Panda. i use this plugin and open it look like open 3rd party application like printhand. it said no deiver found. what must i do then ?

**Comment by kinszhang** [comment]
I think the reason why no device found as your Bluetooth Thermal printer is connected via Bluetooth, instead of via AirPrint(which need the printer connect with your device under the same wireless network). So at first you need to check weather your printer is supported AirPrint(supported device list is here https://support.apple.com/en-us/HT201311). Then make sure both your device and printer are under the same wireless network, and paired before use)
